apiVersion: sourcecov.erda.cloud/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  image: nginx:stable
  env:
    - name: KEY
      value: value
  storageClassName: alicloud-disk-efficiency
  storageSize: 20Gi
  resources:
    limits:
      cpu: "0.1"
      memory: "256Mi"
    requests:
      cpu: "0.1"
      memory: "256Mi"
